//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SitePlanAIPOCEntities : DbContext
    {
        public SitePlanAIPOCEntities()
            : base("name=SitePlanAIPOCEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ReferenceDocument> ReferenceDocuments { get; set; }
        public virtual DbSet<SitePlanDraft> SitePlanDrafts { get; set; }
        public virtual DbSet<SitePlanFinal> SitePlanFinals { get; set; }
        public virtual DbSet<SitePlanRequest> SitePlanRequests { get; set; }
    }
}
