//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceDocument
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string DocumentType { get; set; }
        public Nullable<int> OpenAiFileId { get; set; }
        public Nullable<int> VectorStoreId { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedAtUtc { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
