//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePlanFinal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SitePlanFinal()
        {
            this.SitePlanDrafts = new HashSet<SitePlanDraft>();
        }
    
        public int Id { get; set; }
        public int SitePlanRequestId { get; set; }
        public string SiteOverview { get; set; }
        public string RecommendedLayout { get; set; }
        public string VolunteerFlow { get; set; }
        public string SupplyFlow { get; set; }
        public string Timeline { get; set; }
        public string Risks { get; set; }
        public string PMReviewChecklist { get; set; }
        public string Reviewer { get; set; }
        public string AdditionalNotes { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitePlanDraft> SitePlanDrafts { get; set; }
        public virtual SitePlanRequest SitePlanRequest { get; set; }
    }
}
