//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitePlanRequest
    {
        public int Id { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
        public Nullable<int> VolunteerCount { get; set; }
        public Nullable<int> NumberofLines { get; set; }
        public Nullable<int> MealPackageGoal { get; set; }
        public string RoomSpaceNotes { get; set; }
        public string LoadingNotes { get; set; }
        public string AvaialableEquipment { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string SpecialConstraints { get; set; }
        public string ProjectType { get; set; }
        public string AdditionalNotes { get; set; }
        public string RoomBlueprintFilePath { get; set; }
        public Nullable<System.DateTime> CreatedAtUtc { get; set; }
    }
}
